version: '3.8'

services:
  db:
    image: postgres:15
    container_name: users_profile_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "users"]
      interval: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
